name: Build, Test & Publish

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    name: Build, Test & Publish Docker image
    runs-on: [ self-hosted, linux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -R .

      - name: Set up QEMU (for multi‑arch, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Теги образа: sha и latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/test-runner-demo:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/test-runner-demo:latest

      - name: Run container to verify
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/test-runner-demo:${{ github.sha }}

      - name: Success notice
        run: echo "::notice::Docker image successfully pushed to GHCR and verified!"
