name: Build, Test & Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: [ self-hosted, linux ]

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -R .

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' \
            | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/test-runner-demo:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/test-runner-demo:latest

      - name: Run container to verify
        run: |
          docker run --rm \
            ghcr.io/${{ env.OWNER }}/test-runner-demo:${{ github.sha }}

      - name: Success notice
        run: echo "::notice::Image pushed and verified!"
