name: Build, Test & Publish Docker image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: [self-hosted, linux]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -R .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/test-runner-demo:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/test-runner-demo:latest

      - name: Verify container can start (CI mode)
        run: |
          docker run --rm \
            --privileged \
            --cap-add=NET_ADMIN \
            --cap-add=SYS_MODULE \
            -e CI=true \
            ghcr.io/${{ env.OWNER }}/test-runner-demo:${{ github.sha }}
          echo "::notice::Container started successfully in CI mode"

      - name: Success notice
        run: echo "::notice::Image pushed and verified!"
